sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
after_success:
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - 'lander --upload --ltd-product ldm-633 --pdf LDM-633.pdf --env travis --lsstdoc LDM-633.tex'
env:
  global:
    # LSST the Docs credentials
    - secure: "h7/LLYxSBOnRKGuwAGIFpBMRkaLFakK1HBUA+WfueC8t6Zdwb+U89HTLu03tjbbb3hc5HgbDdf6+g3rwpMxGvMaAx/60SUp/9uTWBIsY4p0rLoYjxMBUk2PlFER6xQbEKmLY+LacU1wzzBYMvFkl0MBV9ND0H3nxVAjQ0tmeoyCYs89lFCS37/XqgilKaBdJqIvN0OXk/w6NNu30ut1ABwPKk+H0+HE1B9wLZJaYzA29+M80NLZzi/exLcH/3y24KRE2m8NDe5o/GFzpdslFqquHIkbTVGsm9m6wAm8Mc2xKT5p6kG+l0eBa9TYfisjO7pDLvWqjKTAdDpbgf0YsChh9Y44CLs8ZeUBEWi3X9jHltktcTzQ93wxVTGzWKyfcfuSj26WDDDGBOewVcGdrBenJZUywTmZvAOuOBJ4kb9Cb+0duOyOda6mtPZbRlMmK+tfGrtL63ciVDM+Ovxumz5BxCmC5SHs/eIm+UP1F35j6HB+Rc0gub2VqdMdC9ccd5nE6gZBgW22tXw6tVrluYcVlQvhsA6knkPv70sMHM4k4E2GzTz+4uOsk83W6TJSXTc9ScW5SULM21DQGD9CaaZl6kSGV9/B6t7E3dQXr10IZcumESMBFlcieMMdAhv8w+saj9uj67cQMU4/HqNCPh+BB6kjaPpYY+6iOwNlR41Y="
    - secure: "NtQfqNLKaDTfFw2dFHghWDm3dlaUyaAqHc+ekLfdLKBpLvDvABYoH6q2jACE3bT1RCE55SLj4h+wnCrjvgXWbFrev5/OdJI23bZlc+CNQmO6kbija/IzWzPiO0m7v1/lPRrxztFWDvxJlRWZbGH5waVJn9gS3bnTfEEaCUC/slvK6EXov+DLX9didffeeUN2GEVSq4WKSzHh57A36qWpitOPPJmpj6KXI0Zq1HjayJVDcKdRCI+va8sIHJ8Pyy9bWYUyirLX5uuVmHbOoEJ+tpu7im+eCVzXVO1D/tL91x7ezijCFiFrkIU3dJcIbum1zAqilpIT1fRcvf1oE3U/UdvGhOS3jrDfJjECm9GzqtPf06fDFGpZO5J6nyKEvqcJx5HsdHE3CN6pRTVMijcjnL/VD6TJxstAOPwfvvMOcW937SnHTi6QJQYY2FeMOwsc/CRIBXwrHbeex4j7msaIxDk/Y/6E1AuthcjwT5FlcNjHzrtvx2AbhvjqHAYilbPRcvoSkR3ckit6DObO5ZTl3s4+3qFCMRYuVwpjw+q1SLsksvw/4zXk5t4FXRMCqK81yQy0C4tYWgEHDSSBFhG0BCOTeBUEhMl9Bh108P7JH36LyIqgMNotunYZehbfxhusgG1EIofpwdoqAvbsZVpT09aXl1BYqgdDrCRXeiRIAjs="
